[feat] : post comment in action

diff --git a/comment/action.yml b/comment/action.yml
--- a/comment/action.yml
+++ b/comment/action.yml
@@ -36,3 +36,29 @@ runs:
         JIRA_BASE_URL: ${{inputs.jira-base-url}}
         TICKET_ID: ${{inputs.ticket-id}}
       run: ${{github.action_path}}/../scripts/check-ticket.sh "$TICKET_ID"
+    
+    - uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026 
+      env:
+        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
+        JIRA_USER_EMAIL: ${{ inputs.jira-username }}
+        JIRA_API_TOKEN: ${{ inputs.jira-token }}
+    
+    - uses: atlassian/gajira-cli@ec286a2b00ebe4cde39f12d888f641411d446723 # commit SHA for tag v3.0.1
+      with:
+        version: 1.0.27
+    
+    - name: Comment on Jira ticket
+      if: steps.check-ticket.outputs.exists == 'true'
+      shell: bash
+      env:
+        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
+        JIRA_API_TOKEN: ${{ inputs.jira-token }}
+        TICKET_ID: ${{ inputs.ticket-id }}
+        COMMENT: ${{ inputs.comment }}
+      run: |
+        jira comment --noedit "$TICKET_ID" --comment="$COMMENT"
+        exit_code=$?
+        if [[ $exit_code -ne 0 ]]; then
+          echo "::error::non-zero exit code: $exit_code"
+          exit 1
+        fi
